Name = 'Nidhi'
Favourite_City = 'Stoke-On-Trent'
morning = 'Yoga is best activity to start the day'
afternoon = 'love to do programming and coding on currunt projects is must at office time'
night = 'reading story books, love it at night time'
goodMoodTalk = "should talk to friends and family "
badMoodTalk = 'mom is the best person to sulani problem you need to spend time in town hall 8 fuck off Google'
sadSong = 'cinema jalan aankhon mein toofan saku Hai'
danceSong = 'everybody knows'
relaxSong = 'music of omkar'
possitiveZone = "should do gargening and spend time with nature"
